### ISSUE TITLE
API Key step missing in ReadMe.

### ISSUE THREAD

**Issue by shaksi** [UseHover/hover-react-sdk#3]
read me does not mention that you need to add api key to the android manifest.

To generate apikey, sign up to userhover.com, and generate new app with your package name. Use the provided key to insert the below in your androidManifest (./android/app/src/main/AndroidManifest.xml)
```
<meta-data
            android:name="com.hover.ApiKey"
            android:value="xxxxx"/>
```
the above can go in new line inside the 

`<application></application>`

**Comment by davkutalek** [comment]
Added, thanks!
