### ISSUE TITLE
Run in background

### ISSUE THREAD

**Issue by coloredlambda** [UseHover/hover-react-sdk#5]
Hi guys, great lib. Is it possible to run USSD in the background without the prompt screen showing up. We are trying to run batch operations using USSD but we are unable to do so, because of the prompt screen that shows up every time a USSD action is run

**Comment by davkutalek** [comment]
Hey @therustydev we do have a version that allows batch operations, but we do have to get some info from you first. Could you please email us at support@usehover.com?
